name: Unit Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.yml'
      - '**.yaml'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'uv.lock'
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.yml'
      - '**.yaml'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'uv.lock'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --dev

    - name: Run unit tests
      run: uv run python -m pytest tests/ -m "not integration" --cov=src --cov-report=term-missing